spring.application.name=hotelApi
server.port = 8080

spring.datasource.url= ${BD_URL}
spring.datasource.username= ${BD_USER}
spring.datasource.password= ${BD_PASSWORD}
spring.datasource.driver-class-name= ${BD_DRIVER}

security.jwt.secret= ${SECRET_KEY_JWT}
security.jwt.issuer= ${SECURITY_JWT_ISSUER}
security.jwt.expiration= ${JWT_EXPIRATION}